Repository galacean/galacean.github.io, pull requests merged in 2021-09, with the labels that each got.

#263 Update lottie docs
  docs/editor-lottie.zh-CN.md
  docs/lottie.md
  docs/lottie.zh-CN.md
Labels: documentation

#264 fix: switch language bug
  docs/editor.zh-CN.md
  package.json
  siteconfig.json
  src/components/Playground/index.tsx
  src/components/home/Footer.tsx
  src/components/home/PBRHelmet.tsx
  src/components/home/Spine.tsx
  src/components/layout/Header.tsx
  src/components/utils.ts
  src/pages/examples.tsx
  src/pages/gltf-viewer.tsx
  src/static/template.html
  src/templates/playground.tsx
Labels: bug

#265 Fix:Chinese and English pictures
  docs/editor-spriteAtlas.zh-CN.md
  docs/first-game.md
  docs/sprite-atlas.zh-CN.md
Labels: documentation

#266 Add example search
  docs/stats.md
  docs/stats.zh-CN.md
  src/components/typedoc/index.less
  src/pages/examples.less
  src/pages/examples.tsx
Labels: bug, feature

#260 feat: 英文化Animator文档 & 增加AnimationEvent Playground
  docs/animator.md
  docs/animator.zh-CN.md
  docs/entity.md
  docs/entity.zh-CN.md
  docs/skeletal-animation.zh-CN.md
  playground/animation-event.ts
Labels: documentation

#270 feat: update script flowchart
  docs/script.md
  docs/script.zh-CN.md
Labels: documentation

#272 fix: api link error
  docs/animator.md
  docs/animator.zh-CN.md
  docs/cube.md
  docs/entity.md
  docs/entity.zh-CN.md
Labels: bug

#274 feat: update script flowchart #270
  docs/script.md
Labels: documentation

#292 rename playground
  playground/buffer-mesh-instance.ts
Labels: bug

#299 fix: Zh_CN version refresh problem
  src/components/layout/index.tsx
Labels: bug

#295 feat: add script blog
  blog/script.zh-CN.md
Labels: documentation
