Repository galacean/galacean.github.io, pull requests merged in 2021-12, with the labels that each got.

#336 Update lottie docs
  docs/lottie.md
  docs/lottie.zh-CN.md
  gatsby/onCreateNode.js
  package.json
  playground/lottie-3d-rotation.ts
  playground/lottie-clips.ts
  siteconfig.json
Labels: documentation

#337 fix: regenerator-runtime
  package.json
  playground/lottie-clips.ts
  src/templates/playground.tsx
Labels: bug

#338 [Playground] add screenshot playground
  playground/screenshot.ts
Labels: playground
