Repository galacean/galacean.github.io, pull requests merged in 2021-08, with the labels that each got.

#156 doc: add doc for 2d
  docs/editor-mars.zh-CN.md
  docs/editor-sprite-mask.zh-CN.md
  docs/editor-sprite-renderer.zh-CN.md
  docs/editor-sprite.zh-CN.md
  docs/sprite.zh-CN.md
Labels: documentation

#112 [Editor Docs]: add gltf resource、 gltf component 、 material resource
  docs/editor-component-gltf.zh-CN.md
  docs/editor-material.zh-CN.md
  docs/editor-model.zh-CN.md
  docs/editor-resource-gltf.zh-CN.md
Labels: documentation

#145 feat: add editor texture and camera manual
  docs/editor-camera.zh-CN.md
  docs/editor-texture.zh-CN.md
Labels: documentation

#161 docs(editor): add assets panel
  docs/editor-assets-panel.zh-CN.md
Labels: documentation

#158 Doc: Light, TextureCubeMap and Collider
  docs/editor-collider.zh-CN.md
  docs/editor-light.zh-CN.md
  docs/editor-textureCubeMap.zh-CN.md
Labels: documentation

#173 fix: animation sample url access bug
  playground/animation.ts
Labels: bug

#172 fix: animation sample image url bug
  playground/animation.ts
Labels: bug

#159 Add editor about doc
  docs/editor-assets-panel.zh-CN.md
  docs/editor-cube.zh-CN.md
  docs/editor-first-step.zh-CN.md
  docs/editor-particle.zh-CN.md
  docs/editor.zh-CN.md
Labels: documentation

#177 [Playground] add ambient light demo
  docs/light.zh-CN.md
  playground/ambient-light.ts
Labels: playground

#149 [Playground]: add light basic playground
  docs/light.zh-CN.md
  playground/light-type.ts
  playground/shadow.ts
Labels: documentation, playground

#179 [playground]: add texture-mipmap demo
  playground/texture-mipmap.ts
Labels: playground

#174 Refactor: adapt to the new material interface
  docs/framebuffer-picker.zh-CN.md
  docs/gltf.zh-CN.md
  docs/light.zh-CN.md
  docs/material.zh-CN.md
  docs/texture.zh-CN.md
  playground/filter-mode.ts
  playground/framebuffer-picker.ts
  playground/gltf-loader.ts
  playground/pbr-base.ts
  playground/pbr-helmet.ts
  playground/primitive-mesh.ts
  playground/probe-reflection.ts
  playground/wrap-mode.ts
  src/components/home/PBRHelmet.tsx
  src/pages/gltf-viewer.tsx
Labels: documentation, playground

#187 Perf: engine docs enhancement
  docs/framebuffer-picker.zh-CN.md
  docs/gltf.zh-CN.md
  docs/light.zh-CN.md
  docs/material.zh-CN.md
  docs/texture.zh-CN.md
  playground/framebuffer-picker.ts
Labels: documentation

#180 [Playground]: Camera Render Target
  playground/render-target.ts
Labels: playground

#157 feat: new playground for collision-detection and raycast
  docs/collision.zh-CN.md
  docs/ray.zh-CN.md
  playground/collision-detection.ts
  playground/raycast.ts
Labels: documentation, playground

#224 feat: add blendShape doc
  docs/model-mesh.zh-CN.md
  playground/skeleton-animation-customBlendShape.ts
Labels: documentation

#223 Playground: add point light for raycast and collision-detection
  playground/collision-detection.ts
  playground/raycast.ts
Labels: enhancement, playground

#222 docs: add background doc and playground
  docs/scene.zh-CN.md
  playground/background.ts
Labels: documentation, playground

#186 [Englishization] engine docs
  docs/artist-bake.md
  docs/artist-unlit.md
  docs/custom-material.md
  docs/framebuffer-picker.md
  docs/gltf.md
  docs/light.md
  docs/material.md
  docs/texture.md
Labels: documentation

#238 Add Independent and Instance Buffer mesh playground
  playground/buffer-mesh-Instance.ts
  playground/buffer-mesh-independent.ts
  playground/buffer-mesh-interleaved.ts
Labels: playground

#236 Playground: MultiCamera MultiViewport OrthCamera
  playground/multi-camera.ts
  playground/multi-viewport.ts
  playground/ortho-switch.ts
Labels: playground

#226 English: raycast and collision detection
  docs/collision.en-US.md
  docs/ray.en-US.md
Labels: documentation

#225 doc: Englishization Engine/Clone/ModelMesh/BufferMesh/MeshRenderer doc
  docs/buffer-mesh.md
  docs/engine.md
  docs/engine.zh-CN.md
  docs/entity-clone.md
  docs/mesh-renderer.md
  docs/model-mesh.md
Labels: documentation

#237 feat:add game demo #100
  docs/first-game.zh-CN.md
  package.json
  playground/flappy-bird.ts
  playground/sprite-sheetAnimation.ts
  plugins/gatsby-transformer-oasis-playground/gatsby-node.js
  siteconfig.json
Labels: documentation, playground

#188 docs: Englishization
  docs/canvas.md
  docs/canvas.zh-CN.md
  docs/lottie.md
  docs/lottie.zh-CN.md
  docs/particle-renderer.md
  docs/particle-renderer.zh-CN.md
  docs/scene.md
  src/components/home/Spine.tsx
Labels: documentation

#253 Englishization/animationClip
  docs/artist-animation-clip.md
  docs/artist-animation-clip.zh-CN.md
Labels: documentation

#257 Englishization/entities
  docs/entity.md
  docs/entity.zh-CN.md
Labels: documentation

#258 feat: 英文化脚本文档
  docs/script.md
Labels: documentation

#259 feat: 英文化第一个脚本文档
  docs/first-script.md
Labels: documentation
