Repository galacean/galacean.github.io, pull requests merged in 2022-11, with the labels that each got.

#497 docs: update hdr docs
  docs/resource-manager.md
  docs/resource-manager.zh-CN.md
Labels: documentation

#495 Add custom font
  docs/font.md
  docs/font.zh-CN.md
Labels: feature

#502 Doc: added timing instructions for track controllers
  docs/controls.md
  docs/controls.zh-CN.md
Labels: documentation

#503 Doc: new WebglEngine
  docs/engine.md
  docs/engine.zh-CN.md
Labels: bug, documentation

#499 fix: adjust search box styles
  src/components/header/index.less
Labels: enhancement

#492 fix: codepen/codesandbox/stackblitz button on demo component
  src/components/Examples/index.tsx
  src/components/Playground/CodeActions.tsx
  src/components/Playground/CodeSandbox.tsx
  src/components/Playground/Codepen.tsx
  src/components/Playground/index.tsx
  src/siteconfig.json
Labels: bug

#489 feat: add env virables
  src/components/Api/util/apiUtil.ts
  src/components/doc/util/docUtil.ts
  src/components/header/headerUtils.ts
  src/components/header/index.tsx
  src/siteconfig.json
  src/utils.ts
Labels: help wanted, feature

#494 fix: hot zone for click event in search box
  src/components/header/components/DocSearchRes.tsx
  src/components/header/components/ExampleSearchRes.tsx
Labels: enhancement

#512 opt material doc
  docs/material.md
  docs/material.zh-CN.md
Labels: enhancement

#524 update shadowsample
  playground/cascade-shadow.ts
  playground/physx-attractor.ts
  playground/physx-compound.ts
  playground/physx-controller.ts
  playground/physx-joint-basic.ts
  playground/physx-raycast.ts
  playground/physx-select.ts
  playground/shadow-basic.ts
  playground/transparent-shadow.ts
Labels: playground

#532 Fix component life cycle error
  docs/script.md
  docs/script.zh-CN.md
Labels: bug

#561 Fix playground link bug
  playground/.dev/vite.config.js
Labels: bug, playground
