Repository galacean/galacean.github.io, pull requests merged in 2023-09, with the labels that each got.

#780 Add sprite animation demo
  playground/animation-sprite.ts
Labels: playground

#745 Add multi scene example
  docs/scene.md
  docs/scene.zh-CN.md
  playground/multi-scene.ts
Labels: playground

#764 Add camera depth texture playground
  playground/camera-depth-texture.ts
  playground/scene-fog.ts
Labels: playground

#768 Add particle example
  playground/benchmark-particle.ts
  playground/particle-dream.ts
  playground/particle-fire.ts
  playground/particle-renderer.ts
  playground/particle-sprite-sheet.ts
  playground/sprite-drawMode.ts
Labels: playground

#792 Adapter to engine latest 1.1
  playground/benchmark-particle.ts
  playground/particle-dream.ts
  playground/particle-fire.ts
Labels: playground

#791 Update particle renderer, camera depth texture and clone doc
  docs/camera.md
  docs/camera.zh-CN.md
  docs/custom-material.md
  docs/custom-material.zh-CN.md
  docs/entity-clone.md
  docs/entity-clone.zh-CN.md
  docs/particle-renderer.md
  docs/particle-renderer.zh-CN.md
Labels: documentation

#803 Update particle renderer, camera depth texture and clone doc
  docs/camera.md
  docs/camera.zh-CN.md
  docs/custom-material.md
  docs/custom-material.zh-CN.md
  docs/entity-clone.md
  docs/entity-clone.zh-CN.md
  docs/particle-renderer.md
  docs/particle-renderer.zh-CN.md
Labels: documentation

#789 add bake doc
  docs/ambient-light.md
  docs/ambient-light.zh-CN.md
  docs/editor-3d-light.zh-CN.md
  docs/gltf.md
  docs/gltf.zh-CN.md
Labels: documentation

#811 Add render priority
  docs/editor-sprite-renderer.zh-CN.md
  docs/sprite-renderer.md
  docs/sprite-renderer.zh-CN.md
Labels: documentation

#795 Add shaderLab doc
  docs/shader-lab.md
  docs/shader-lab.zh-CN.md
  playground/shader-lab-simple.ts
Labels: documentation

#820 refactor: editor doc
  docs/editor.zh-CN.md
Labels: documentation

#838 fix redirect and blockquote bugs
  src/components/Api/index.tsx
  src/components/Examples/index.tsx
  src/components/contextProvider/index.tsx
  src/components/doc/components/DocDetail.tsx
  src/components/doc/index.tsx
Labels: bug
