Repository galacean/galacean.github.io, pull requests merged in 2023-07, with the labels that each got.

#760 Update input doc
  docs/input.md
  docs/input.zh-CN.md
Labels: documentation

#761 Fix sprite sheet ani bug
  playground/sprite-sheetAnimation.ts
Labels: bug

#753 Add video benchmark demo
  docs/texture-2D.zh-CN.md
  docs/texture-2d.md
  package.json
  playground/benchmark-video.ts
  playground/video-background.ts
Labels: feature
